name: xChat
author: Rysieeku
version: 1.3.1
main: Rysieeku\xChat\Main
api: [3.0.0-ALPHA6]
commands:
  xchat:
    description: Main plugin command.
    aliases: [c, chat]
permissions:
  xchat.clear:
    default: op
  xchat.info:
    default: op
  xchat.help:
    default: op
  xchat.enable:
    default: op
  xchat.disable:
    default: op
  xchat.mute:
    default: op
  xchat.unmute:
    default: op
  xchat.reload:
    default: op
  xchat.*:
    default: op
