name: xChat
author: Rysieeku
version: 1.1
main: Rysieeku\Main
api: [3.0.0-ALPHA6]
commands:
  xchat:
    description: Main plugin command.
    aliases: [c, chat]
permissions:
  xchat.chat.clear:
    default: false
  xchat.cmd.info:
    default: false
  xchat.cmd.help:
    default: false
  xchat.chat.enable:
    default: false
  xchat.chat.disable:
    default: false
  xchat.reload:
    default: false
  xchat.*:
    default: false
